### ISSUE TITLE
Electron Cash crashes if sending transaction and entering password incorrectly

### ISSUE THREAD

**Issue by n9jd34x04l151ho4** [fyookball/electrum#295]
Steps to reproduce:
1) Try send a small amount, it prompts for password
2) Enter the password incorrectly
3) Crashes with garbled dialog on top of main window but closing the Please wait dialog does not work. Need to restart Electron Cash.

![electroncash-bad-password-crash](https://user-images.githubusercontent.com/31981309/33306512-0454255c-d3fa-11e7-8d3e-da51ce1286b9.png)

```
$ Traceback (most recent call last):
  File "/home/n/electron-cash-installation/ElectronCash-2.9.4/gui/qt/util.py", line 583, in run
    result = task.task()
  File "/home/n/electron-cash-installation/ElectronCash-2.9.4/lib/wallet.py", line 1112, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/n/electron-cash-installation/ElectronCash-2.9.4/lib/keystore.py", line 107, in sign_transaction
    self.check_password(password)
  File "/home/n/electron-cash-installation/ElectronCash-2.9.4/lib/keystore.py", line 303, in check_password
    xprv = pw_decode(self.xprv, password)
  File "/home/n/electron-cash-installation/ElectronCash-2.9.4/lib/bitcoin.py", line 144, in pw_decode
    raise InvalidPassword()
InvalidPassword: Incorrect password
```

**Comment by fyookball** [comment]
couldnt recreate in 3.1.2. i assume its fixed.
