### ISSUE TITLE
Electron Cash message signing doesn't work

### ISSUE THREAD

**Issue by awemany** [fyookball/electrum#320]
Hey,

for the BU voting system at https://www.bitcoinunlimited.info/voting/

I tried signing messages using EC on Linux in the GUI. But I got, on the console:
```
Traceback (most recent call last):
  File ".../Electron Cash-2.9.4/gui/qt/main_window.py", line 1913, in <lambda>
    b.clicked.connect(lambda: self.do_sign(address_e, message_e, signature_e))
  File ".../Electron Cash-2.9.4/gui/qt/main_window.py", line 1242, in request_password
    return func(self, *args, **kwargs)
  File ".../Electron Cash-2.9.4/gui/qt/main_window.py", line 1852, in do_sign
    address  = address.text().strip()
AttributeError: 'QString' object has no attribute 'strip'
```

**Comment by kyuupichan** [comment]
Try the 3.0 just released.  If you can edit the code you could wrap the address.text() bit in a str()....
