### ISSUE TITLE
Load from QR: Electron cash was unable to parse your transaction

### ISSUE THREAD

**Issue by estevaocm** [fyookball/electrum#326]
Hello, 

When I attempt to load an Electron transaction from the QR scanner in Debian/Ubuntu, I get: "Electron cash was unable to parse your transaction".

I can load from QR using Electrum and Electrum-LTC, but Electron Cash is failing.

Details below:

Traceback (most recent call last):
  File "/home/estevao/Downloads/Electron-Cash-2.9.4/gui/qt/main_window.py", line 1995, in tx_from_text
    tx.deserialize()
  File "/home/estevao/Downloads/Electron-Cash-2.9.4/lib/transaction.py", line 588, in deserialize
    d = deserialize(self.raw)
  File "/home/estevao/Downloads/Electron-Cash-2.9.4/lib/transaction.py", line 458, in deserialize
    d['outputs'] = list(parse_output(vds,i) for i in xrange(n_vout))
  File "/home/estevao/Downloads/Electron-Cash-2.9.4/lib/transaction.py", line 458, in <genexpr>
    d['outputs'] = list(parse_output(vds,i) for i in xrange(n_vout))
  File "/home/estevao/Downloads/Electron-Cash-2.9.4/lib/transaction.py", line 436, in parse_output
    d['value'] = vds.read_int64()
  File "/home/estevao/Downloads/Electron-Cash-2.9.4/lib/transaction.py", line 109, in read_int64
    def read_int64(self): return self._read_num('<q')
  File "/home/estevao/Downloads/Electron-Cash-2.9.4/lib/transaction.py", line 147, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
error: unpack_from requires a buffer of at least 8 bytes

**Comment by estevaocm** [comment]
Excuse me, I will test with the new release and get back to this issue.

**Comment by estevaocm** [comment]
This issue was solved in release 3.0.
