### ISSUE TITLE
Sweep dialog TypeError: argument 1 has unexpected type 'Address'

### ISSUE THREAD

**Issue by tinybike** [fyookball/electrum#338]
I get the following error when I try to open the Wallet -> Private keys -> Sweep dialog box in the electron-cash GUI:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/Electron_Cash-3.0-py3.5.egg/electroncash_gui/qt/main_window.py", line 2403, in sweep_key_dialog
    h, address_e = address_field(addresses)
  File "/usr/lib/python3.5/site-packages/Electron_Cash-3.0-py3.5.egg/electroncash_gui/qt/util.py", line 306, in address_field
    address_e.setText(addresses[0])
TypeError: QLineEdit.setText(str): argument 1 has unexpected type 'Address'
```
I'm using Linux (Xubuntu 16.04), and get the same error in both the pre-built binary and the setup.py installed version.

The sweep dialog works fine for me using v2.9.4 (commit f493cadbcbb1572a5f28d10a1c4f84085f38fffa).

**Comment by kyuupichan** [comment]
Yes sweeping is broken on master branch. Use Python3 branch of it matters

**Comment by kyuupichan** [comment]
Should be fixed in master
