### ISSUE TITLE
missing input values in (old?) transactions from history

### ISSUE THREAD

**Issue by molecular** [fyookball/electrum#342]
to reproduce...

  * right-click a transaction on history tab, choose "details"
  * click "save" button, choose file
  * observe error:

```
warning: deprecated tx.hash()
Traceback (most recent call last):
  File "/home/nick/bitcoin/electron-cash/gui/qt/transaction_dialog.py", line 172, in save
    input_values = [x['value'] for x in self.tx.inputs()]
  File "/home/nick/bitcoin/electron-cash/gui/qt/transaction_dialog.py", line 172, in <listcomp>
    input_values = [x['value'] for x in self.tx.inputs()]
KeyError: 'value'
Aborted (core dumped)
```

**Comment by kyuupichan** [comment]
This has just been fixed on master and python3 branches by https://github.com/fyookball/electrum/pull/345

**Comment by molecular** [comment]
yep, it's fixed. Thanks a lot.
