### ISSUE TITLE
trezor: signing fails

### ISSUE THREAD

**Issue by molecular** [fyookball/electrum#343]
signing fails when using a cash address, but also when using a legacy address

```
[DeviceMgr] end client for keystore
Traceback (most recent call last):
  File "/home/nick/bitcoin/electron-cash/gui/qt/util.py", line 587, in run
    result = task.task()
  File "/home/nick/bitcoin/electron-cash/lib/wallet.py", line 1152, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/plugin.py", line 56, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/plugin.py", line 230, in sign_transaction
    outputs = self.tx_outputs(keystore.get_derivation(), tx)
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/plugin.py", line 350, in tx_outputs
    txoutputtype.address = address
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 662, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/type_checkers.py", line 177, in CheckValue
    raise TypeError(message)
TypeError: <Address qpa2tcq58mhkd76q6ct4s6kfr4y9pu3245ypf36qch> has type <class 'electroncash.address.Address'>, but expected one of: (<class 'bytes'>, <class 'str'>)
```

**Comment by kyuupichan** [comment]
@molecular  - please confirm; I don't have a trezor handy to test.

**Comment by molecular** [comment]
confirming it's fixed. Thank you!
