### ISSUE TITLE
UnicodeDecodeError at import bitcoin wallet

### ISSUE THREAD

**Issue by panaceya** [fyookball/electrum#371]
Hello!

I trying import  bitcoin wallet, but receive next error:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.0-py3.5.egg/electroncash_gui/qt/qrtextedit.py", line 49, in file_input
    data = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 52: ordinal not in range(128)
Aborted
```

```bash
$ pip3 freeze | grep -i elec
Electron-Cash==3.0
$ lsb_release -a
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon User Edition 5.11
Release:        16.04
Codename:       xenial
$ python3 --version
Python 3.5.2
```

Error also exist in git.

**Comment by kyuupichan** [comment]
I've changed the code to assume UTF-8 in git.  Can you try there?

**Comment by kyuupichan** [comment]
In master branch

**Comment by panaceya** [comment]
Hello!

Have another error:
```
Traceback (most recent call last):
  File "/home/panaceya/git/electrum/gui/qt/qrtextedit.py", line 50, in file_input
    data = f.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 52: invalid start byte
Aborted
```

**Comment by rt121212121** [comment]
Can you provide a wallet file which when imported causes this error?

**Comment by fyookball** [comment]
looks very similar to #284 which appears fixed.  Closing.

**Comment by panaceya** [comment]
For me not fixed.

**Comment by fyookball** [comment]
@panaceya can this be recreated now or only happens w old wallet

**Comment by rt121212121** [comment]
You need to import a wallet as a wallet, you can't import it via the way you are trying to do it.  That is for text files with addresses in them, maybe one on each line or something.   This is a bug in that it does not catch the error and show a ui failure notification.  Issue #613 has a commit for that.
