### ISSUE TITLE
unable to run on OSX 10.9.5

### ISSUE THREAD

**Issue by neoice** [fyookball/electrum#372]
```
Traceback (most recent call last):
  File "/Users/neoice/Applications/Electron-Cash.app/Contents/Resources/__boot__.py", line 98, in <module>
    _run()
  File "/Users/neoice/Applications/Electron-Cash.app/Contents/Resources/__boot__.py", line 82, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/neoice/Applications/Electron-Cash.app/Contents/Resources/electron-cash.py", line 379, in <module>
    d.init_gui(config, plugins)
  File "electroncash/daemon.pyc", line 282, in init_gui
  File "electroncash_gui/qt/__init__.pyc", line 35, in <module>
  File "PyQt5/QtGui.pyc", line 14, in <module>
  File "PyQt5/QtGui.pyc", line 10, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Users/neoice/Applications/Electron-Cash.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtGui.so, 2): Symbol not found: _LSCopyDefaultApplicationURLForURL
  Referenced from: /Users/neoice/Applications/Electron-Cash.app/Contents/MacOS/./../Frameworks/QtCore.framework/Versions/5/QtCore
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
 in /Users/neoice/Applications/Electron-Cash.app/Contents/MacOS/./../Frameworks/QtCore.framework/Versions/5/QtCore
2017-12-21 19:01:59.357 Electron-Cash[16732:507] Electron-Cash Error
```

a quick Google search suggests that `Symbol not found: _LSCopyDefaultApplicationURLForURL` has been removed from Qt5 :(

**Comment by cculianu** [comment]
Hey man this has been addressed in the latest 3.1.  It should run now!
