### ISSUE TITLE
BaseException: ('Redeem script required for', 'p2sh', 'redacted') 

### ISSUE THREAD

**Issue by butterstuff** [fyookball/electrum#381]
hi fyook, happy holidays.  i happened to run into this problem  tonight in trying to claim my bch. I noticed the other thread with the similar issue but decided not to hijack it.

 i am running electron on linux in a vm and imported a series of private keys from an emptied btc wallet and upon hitting "next" i got the "please wait" / install wizard dialog and this was returned in the terminal...

^T^TTraceback (most recent call last):
  File "/home/user/Desktop/Electron Cash-3.0/gui/qt/main_window.py", line 441, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/home/user/Desktop/Electron Cash-3.0/gui/qt/__init__.py", line 200, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/user/Desktop/Electron Cash-3.0/gui/qt/installwizard.py", line 278, in run_and_get_wallet
    self.run(action)
  File "/home/user/Desktop/Electron Cash-3.0/lib/base_wizard.py", line 60, in run
    f(*args)
  File "/home/user/Desktop/Electron Cash-3.0/lib/base_wizard.py", line 86, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)                                  
  File "/home/user/Desktop/Electron Cash-3.0/gui/qt/installwizard.py", line 91, in func_wrapper                                      
    run_next(*out)                                                                                                                   
  File "/home/user/Desktop/Electron Cash-3.0/lib/base_wizard.py", line 96, in on_wallet_type                                         
    self.run(action)                                                                                                                 
  File "/home/user/Desktop/Electron Cash-3.0/lib/base_wizard.py", line 60, in run                                                    
    f(*args)                                                                                                                         
  File "/home/user/Desktop/Electron Cash-3.0/lib/base_wizard.py", line 134, in import_addresses_or_keys                              
    self.add_xpub_dialog(title=title, message=message, run_next=self.on_import, is_valid=v)                                          
  File "/home/user/Desktop/Electron Cash-3.0/gui/qt/installwizard.py", line 91, in func_wrapper                                      
    run_next(*out)                                                                                                                   
  File "/home/user/Desktop/Electron Cash-3.0/lib/base_wizard.py", line 146, in on_import                                             
    self.wallet.import_private_key(x, None)                                                                                          
  File "/home/user/Desktop/Electron Cash-3.0/lib/wallet.py", line 1499, in import_private_key                                        
    raise BaseException('Redeem script required for', txin_type, sec)                                                                
BaseException: ('Redeem script required for', 'p2sh', '<<redacted>>')        

*note that last bit was redacted by me for security*

the electron BCH wallet is standard type.
the electrum BTC wallet was originally 2FA, but I restored it from seed to disable the 2FA before transferring all my funds to a new seed/wallet as the first measure before using electron to claim BCH.

something to note:  the addresses associated with the keys i am importing start with 3xxxx.  
when i tried to originally restore the Electron Cash wallet from my btc seed, all the addresses that show up start with 1xxxx and are all 0 tx values.

thus, i attempted to manually import the priv keys, giving me this base exception error

i am pretty new to this - so please excuse me if ive misrepresented any info or have missed some larger point or issue that you have already solved 1000x.  I have seen a few threads about 2fa or multisig issues but they were a bit over my head and i was not sure if it was related.

thanks in advance and merry chrismakwanzakkah

**Comment by butterstuff** [comment]
update:  i have managed to create a watch-only wallet with the correct funds.  still not able to create a standard wallet

**Comment by butterstuff** [comment]
update2:  solved my own issue.

found this thread
https://bitcointalk.org/index.php?topic=2433700.0

it fixes the issue perfectly.

for posterity:

(obviously move all BTC to new address)
restore seed to 2fa disabled wallet without encryption
opened wallet in text editor.
locate x1 and x2 xprv
locate x3 xpub


1. Open ElectronCash
2. File -> New\Restore -> MultiSig Wallet
3. Set "From 3 cosigners", "requires 2 signatures"
4. "Use public or private keys"
5. Paste in the "X1" xprv from your disabled 2FA wallet
6. When prompted for co-signer 2, "Enter Co-signer key"
7. Paste in the "X2" xprv from your disabled 2FA wallet
8. When prompted for co-singer 3, "Enter Co-singer key"
9. Paste in the "X3" xpub from your disabled 2FA wallet.


and voila.
