### ISSUE TITLE
Linux Electron Cash 3.1 can't open wallet

### ISSUE THREAD

**Issue by 94b42c29dd** [fyookball/electrum#420]
I upgraded Electron Cash from 3.0 to 3.1 on a debian based system. Now i can't open (any) wallet anymore, even if i just created it, the program just disappears. Everything worked fine in 3.0. This is what happens in console:
Traceback (most recent call last):
  File "/usr/local/bin/electron-cash", line 5, in <module>
    pkg_resources.run_script('Electron-Cash==3.1', 'electron-cash')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 55, in execfile
    exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/EGG-INFO/scripts/electron-cash", line 373, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/electroncash/daemon.py", line 284, in init_gui
    self.gui.main()
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/electroncash_gui/qt/__init__.py", line 251, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/electroncash_gui/qt/__init__.py", line 210, in start_new_window
    wallet.start_threads(self.daemon.network)
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/electroncash/wallet.py", line 996, in start_threads
    self.synchronizer = Synchronizer(self, network)
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/electroncash/synchronizer.py", line 55, in __init__
    self.initialize()
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/electroncash/synchronizer.py", line 186, in initialize
    self.subscribe_to_addresses(self.wallet.get_addresses())
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/electroncash/synchronizer.py", line 76, in subscribe_to_addresses
    hashes = [addr.to_scripthash_hex() for addr in addresses]
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/electroncash/synchronizer.py", line 76, in <listcomp>
    hashes = [addr.to_scripthash_hex() for addr in addresses]
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/electroncash/address.py", line 432, in to_scripthash_hex
    return hash_to_hex_str(self.to_scripthash())
  File "/usr/local/lib/python3.4/dist-packages/Electron_Cash-3.1-py3.4.egg/electroncash/address.py", line 80, in hash_to_hex_str
    return bytes(reversed(x)).hex()
AttributeError: 'bytes' object has no attribute 'hex'

**Comment by kyuupichan** [comment]
You need python 3.5 or higher. @fyookball please update the Python requirements

**Comment by Brad-R** [comment]
I encountered this problem too.  Would it be possible to have electron-cash detect the python version, and exit gracefully with a warning, rather than crashing with a flood of error messages?
