### ISSUE TITLE
Electron Cash 3.1.2 dependency issues

### ISSUE THREAD

**Issue by divingtime** [fyookball/electrum#459]
I have been using and enjoying Electron Cash, but the 3.1.2 update won't install properly on my Debian Jessie setup.  Let me paste in my terminal printout followed by the root log showing the errors.  I believe I have the latest and greatest python stuff running.  BTW -- the latest electrum installed easily on this same Debian VM.  I think you guys use the same python dependencies.  Looking for suggestions, and to confirm whether or not something is missing in the 3.1.2 update for "installing" on Debian.  The download was gpg verified and passed.  I have used pip install at all times in the past, is there a different way (see terminal)?

joe@debian-vm:~$ sudo pip3 install /home/joe/Desktop/ElectronCash-3.1.2.tar.gz
[sudo] password for joe: 
Unpacking ./Desktop/ElectronCash-3.1.2.tar.gz
  Running setup.py (path:/tmp/pip-6_36tbe4-build/setup.py) egg_info for package from file:///home/joe/Desktop/ElectronCash-3.1.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyaes>=0.1a1 in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.9 in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): pbkdf2 in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): qrcode in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): protobuf in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): dnspython in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): jsonrpclib-pelix in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): PySocks>=1.6.6 in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Downloading/unpacking pyqt5 (from Electron-Cash==3.1.2)
  Could not find any downloads that satisfy the requirement pyqt5 (from Electron-Cash==3.1.2)
Cleaning up...
No distributions at all found for pyqt5 (from Electron-Cash==3.1.2)
Storing debug log for failure in /root/.pip/pip.log
joe@debian-vm:~$ 

------------------------------------------------------------
/usr/bin/pip3 run on Thu Jan 11 21:00:02 2018
Unpacking ./Desktop/ElectronCash-3.1.2.tar.gz
  Running setup.py (path:/tmp/pip-cpecg3yy-build/setup.py) egg_info for package from file:///home/joe/Desktop/ElectronCash-3.1.2.tar.gz
    running egg_info
    creating pip-egg-info/Electron_Cash.egg-info
    writing top-level names to pip-egg-info/Electron_Cash.egg-info/top_level.txt
    writing requirements to pip-egg-info/Electron_Cash.egg-info/requires.txt
    writing dependency_links to pip-egg-info/Electron_Cash.egg-info/dependency_links.txt
    writing pip-egg-info/Electron_Cash.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/Electron_Cash.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/Electron_Cash.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/Electron_Cash.egg-info/SOURCES.txt'
  Source in /tmp/pip-cpecg3yy-build has version 3.1.2, which satisfies requirement Electron-Cash==3.1.2 from file:///home/joe/Desktop/ElectronCash-3.1.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyaes>=0.1a1 in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.9 in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): pbkdf2 in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages (from Electron-Cash==3.1.2)
  skipping extra security
  skipping extra security
  skipping extra security
Requirement already satisfied (use --upgrade to upgrade): qrcode in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): protobuf in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): dnspython in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): jsonrpclib-pelix in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Requirement already satisfied (use --upgrade to upgrade): PySocks>=1.6.6 in /usr/local/lib/python3.4/dist-packages (from Electron-Cash==3.1.2)
Downloading/unpacking pyqt5 (from Electron-Cash==3.1.2)
  Getting page https://pypi.python.org/simple/pyqt5/
  URLs to search for versions for pyqt5 (from Electron-Cash==3.1.2):
  * https://pypi.python.org/simple/pyqt5/
  Analyzing links from page https://pypi.python.org/simple/pyqt5/
    Skipping https://pypi.python.org/packages/01/8c/9d36bcb04f3c21bd449e438a5d52259a62dbbfe222698fa006099caf5143/PyQt5-5.8.1.1-5.8.0-cp35.cp36.cp37-none-win_amd64.whl#md5=04b2cb03efe5f544725f729eef723d28 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/03/03/f42a3f893c4f7b08dfc3f6187b2db5558ee3ca194180bbd8b85b8721e825/PyQt5-5.9.1-5.9.2-cp35.cp36.cp37-none-win32.whl#md5=c88436dda54af7c759fa149d76eeca87 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/07/7b/3223e33293be19e7666976db4ed346d83ba9b97be23aae2e4f94dcf37782/PyQt5-5.8.2-5.8.0-cp35.cp36.cp37-none-win32.whl#md5=1680375206a128d8325fb38efd784c03 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/0f/a8/71d918272a9ae17541942daffb15d663d7c9401346252a495a84822e81d5/PyQt5-5.8.2-5.8.0-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl#md5=2b71949cfc748db399c0bd8157444a85 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/12/8a/83d96cef5f8155bc4eb140713bc479f56c15e542bec0c4340f65a0e8317a/PyQt5-5.7.1-5.7.1-cp34.cp35.cp36-abi3-manylinux1_x86_64.whl#md5=b4f4f015c60c6c6f0404acf3307b31c1 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/13/f4/dad8682ca966094fd3694746fba6b87c11ba793a4660022db7275d50b34b/PyQt5-5.8-5.8.0-cp34.cp35.cp36.cp37-abi3-manylinux1_x86_64.whl#md5=a2fdd5e3671aaef944c1a83ca1eaf60a (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/14/60/cc8aacfc5c7fd1eb54aa91982d189b052100b2884ba7bc77b3515879a17d/PyQt5-5.9-5.9.1-cp35.cp36.cp37-none-win32.whl#md5=640473b50f6387c08fd84349793460ba (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/21/a9/f64e3511b2e7da37447afc34d3f28d0a5b00e0cfdf5774171f9f11bfd722/PyQt5-5.9.1-5.9.2-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl#md5=6bb5a992af1c817c599544f0099a0c39 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/26/97/b40b1052ffc676c9fb5e68cb0400309a9a22a4f582aa4294b319f3dc8b3f/PyQt5-5.8.1.1-5.8.0-cp35.cp36.cp37-none-win32.whl#md5=f486111e89542660ac29cfd791644b8b (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/28/9e/ae20f544f99f6e5b28d806bf2c37b7069c8bb3fd7bdf84e6ed02ee853591/PyQt5-5.9-5.9.1-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl#md5=bf07195ac2b81821ade2bc51762784c9 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/34/a7/ed3a2e7f74a7fcc112c1669968ca1be552f34d123bb4515a97520d69e8f3/PyQt5-5.6-cp35-cp35m-manylinux1_x86_64.whl#md5=787c331fb9b462a16f8526c964023c58 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/3a/c6/26270f5550f00920045c2f0b222a7d03d7a64382825c68bf0bb1a51d854c/PyQt5-5.9.2-5.9.3-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl#md5=7af06d4bd8360b710e62e0c21e7f110d (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/3b/08/32236a8fb73e4dfe51c8091a58ac24cc4987d1b12630a68939ebb6126d45/PyQt5-5.8-5.8.0-cp34.cp35.cp36.cp37-abi3-macosx_10_6_intel.whl#md5=73745a08f3cc1690922b6e21be341f43 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/3c/34/a768dacf653a883f57928ed971575c29f80b87db09a52c9b66724d6317a0/PyQt5-5.7-cp35-none-win_amd64.whl#md5=43f6617cd9d109ad334d55a1e2f8eecb (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/40/f9/0be162881f4bdb6e828ee6db871310140a5278b4538e65716eae8b2d3dbd/PyQt5-5.6-cp35-cp35m-macosx_10_6_intel.whl#md5=51c8e78f58777eb71e0304ed8a35153d (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/45/63/353403622330d335631ec3a3016f9e0a6a9519082488b1421003682f8ef4/PyQt5-5.9-5.9.1-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl#md5=785f1aa6027e2b691b9117629657f104 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/4f/52/428af82f860dae1e08f8cb7f03399a9cc0f3756f2bd1b3e31ee749e126e4/PyQt5-5.8.2-5.8.0-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl#md5=4c2c1577d8766b4ce6f328635b9556fe (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/53/47/c3af02173da1c6887de05ec6201f8582eee4efcd9476d47739b42cb1a8b9/PyQt5-5.9-5.9.1-cp35.cp36.cp37-none-win_amd64.whl#md5=93e37890bcec8009ede4a39faaad96c6 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/55/08/a8cae8689ed928a6c7eba2e125b5cf96545995692d144d8b8f6471e47246/PyQt5-5.8.2-5.8.0-cp35.cp36.cp37-none-win_amd64.whl#md5=ab236f946ce9f7819a1e240b41e4d6ef (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/5c/9b/c5a06dccbf7db02c83adca82321f4b8e97aaf088d73eb5fc52f4f1463399/PyQt5-5.7.1-5.7.1-cp34.cp35.cp36-abi3-macosx_10_6_intel.whl#md5=6f3d3496505a39c44aed09fca0850f2c (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/5e/41/93bf8f289b476bc5d8cece7948a166cbcea761f5b1262e5fdd7076a5e02a/PyQt5-5.9.2-5.9.3-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl#md5=926b3841d74d178171a2bbc0946fe2a4 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/67/ad/5ce6033bded3c39043a2c67cc46b3976427187f68c9dbaf5533884899086/PyQt5-5.9.2-5.9.3-cp35.cp36.cp37-none-win_amd64.whl#md5=87f07e234e60dfc3a81d8b59862fb258 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/71/c5/7e2a35682358f1be16f5f310e7ea3b64c5ecc168f83c3dc4d50dcee9f087/PyQt5-5.7-cp35-none-win32.whl#md5=f52427b4706eb4f9a371ef5d8c02c9ac (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/87/e2/c31ca63e04c2b0ed8cf7d5afd564f1d254d684ae3b62cbc3c6c48f2875a1/PyQt5-5.8.1.1-5.8.0-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl#md5=8fbb4ec4c8d7b3d510728625b9f9d24f (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/a0/b1/95c3b2cf3c0dc50315413857a1f67c4fd6e86c609c5f3e01a38b331a23eb/PyQt5-5.9.2-5.9.3-cp35.cp36.cp37-none-win32.whl#md5=f9ae1dc57b560235f2dcd6a97c358687 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/b4/07/300a655328833b05646c6af50cfef795e4aaa5e58727f6b551c62e9ab173/PyQt5-5.8.1.1-5.8.0-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl#md5=60a2fbe677fb9c4d5968a6c0292872f7 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/cc/eb/f2e115d21abec6d86b2af0b7fa6f71439767d0a91cb393607e4f72998b0a/PyQt5-5.6-cp35-none-win32.whl#md5=517c5bf65e2cb43a8f187a8674499e73 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/d0/e4/0fb306a86f0471d69e4f8c501def0af5dd5468cdcb47ccf68c0703e32571/PyQt5-5.7-cp35-cp35m-macosx_10_6_intel.whl#md5=bd4261df379dc4d704f1c04cd9ae784c (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/d4/e2/369af0102c2fdd2c6fcd77dbd87c28342ca479959f3432c4209f0b29c660/PyQt5-5.7.1-5.7.1-cp34.cp35.cp36-none-win_amd64.whl#md5=7c7c2b530c8e812e4e697793a313cdad (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/d8/d4/55e78a986b50f6551ba09d523a11d67535b3397b295e1ccedfaeaa26b88b/PyQt5-5.7.1-5.7.1-cp34.cp35.cp36.cp37-none-win32.whl#md5=8fe27302395174e5ccdfe74b8fff5221 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/ea/6c/144ffca9f680986a1d48a7f42315933bfc100659447971180474be171b59/PyQt5-5.9.1-5.9.2-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl#md5=c19f6d1eed5f7d4fbb390b9662899a89 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/eb/e0/28b46c12a176329cfa1f57aba29c04f22bd98f1ffcad02f50013f4933c2f/PyQt5-5.9.1-5.9.2-cp35.cp36.cp37-none-win_amd64.whl#md5=9d9053f6de3299169beae09c16dd0b99 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/f0/3a/8f2261c0477008057636b9f992952033748b9ee94541dd54373f7d6bf5f1/PyQt5-5.8-5.8.0-cp34.cp35.cp36.cp37-none-win32.whl#md5=ca36b1bace7cf374e9223ffdb0e137b4 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/f3/4d/8ef2d9db0a0450de985dfe04d64d09762ab2205179914aa3cc41f44af377/PyQt5-5.6-cp35-none-win_amd64.whl#md5=29243c64de9dc213221e3d13b18318bd (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/f3/94/92e7c8b3c2279a3503a8ba41fce5e0234acdc6de3a1b278ebfdcfe532f67/PyQt5-5.7-cp35-cp35m-manylinux1_x86_64.whl#md5=e745c4331a3fbafb9b59636089d5bf9f (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/f9/b4/54bd54fa47b8c9f2c3460c25f40ecc1ffa749b9e86ed39982be488660c33/PyQt5-5.8-5.8.0-cp34.cp35.cp36.cp37-none-win_amd64.whl#md5=53f7cf0d09f45c9e434ae2dbd63ecc15 (from https://pypi.python.org/simple/pyqt5/) because it is not compatible with this Python
  Could not find any downloads that satisfy the requirement pyqt5 (from Electron-Cash==3.1.2)
Cleaning up...
No distributions at all found for pyqt5 (from Electron-Cash==3.1.2)
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
pip.exceptions.DistributionNotFound: No distributions at all found for pyqt5 (from Electron-Cash==3.1.2)

**Comment by divingtime** [comment]
I also noticed there is a no package thread running on 3.0 from awhile ago.  I don't see where that was ever handled here.  On the surface it sounds like the same issue, although I am doing a full install.

**Comment by marceloneil** [comment]
Can you format this using the "```" code tags?

**Comment by mariansoban** [comment]
Same issue for me, 
for 
`sudo python3 setup.py install`

I'm getting

```
Installed /usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.2-py3.5.egg
Processing dependencies for Electron-Cash==3.1.2
Searching for pyqt5
Reading https://pypi.python.org/simple/pyqt5/
No local packages or download links found for pyqt5
error: Could not find suitable distribution for Requirement.parse('pyqt5')
```

Before installation of Electron Cash, I've run:

`sudo apt-get install git dirmngr python3-pyqt5 python3-setuptools`

which includes some sort of pyqt5.

My environment: Clean Ubuntu 16.04.3 64bit
Any hint's how to fix this issue?

**Comment by mariansoban** [comment]
In the end I was able to fix missging pyqt5 dependency as follows:
````
sudo apt-get install python3-pip
# https://pypi.python.org/simple/pyqt5/
wget https://pypi.python.org/packages/3a/c6/26270f5550f00920045c2f0b222a7d03d7a64382825c68bf0bb1a51d854c/PyQt5-5.9.2-5.9.3-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl#md5=7af06d4bd8360b710e62e0c21e7f110d
sudo pip3 install PyQt5-5.9.2-5.9.3-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl
````

**Comment by fyookball** [comment]
weird that this just started happening, doesnt seem related to Electron Cash though, is it?
