### ISSUE TITLE
'TxInputType' object has no attribute 'amount'

### ISSUE THREAD

**Issue by Dehumanizer77** [fyookball/electrum#46]
When I try to send (using Trezor HW wallet), I'm getting this error popped up.

![screenshot at 2017-08-03 19-30-07](https://user-images.githubusercontent.com/1876451/28939565-061be6a4-7892-11e7-8ebf-dfc28698254a.png)

**Comment by Dehumanizer77** [comment]
here is the traceback from console:

Traceback (most recent call last):
  File "/home/johny/electrum/gui/qt/util.py", line 582, in run
    result = task.task()
  File "/home/johny/electrum/lib/wallet.py", line 1103, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/johny/electrum/plugins/trezor/plugin.py", line 66, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/johny/electrum/plugins/trezor/plugin.py", line 240, in sign_transaction
    inputs = self.tx_inputs(tx, True)
  File "/home/johny/electrum/plugins/trezor/plugin.py", line 307, in tx_inputs
    txinputtype.amount = txin['value']
AttributeError: 'TxInputType' object has no attribute 'amount'

**Comment by danny91** [comment]
I also have this issue

**Comment by fyookball** [comment]
should be fixed in latest code for non MS trezor

**Comment by danny91** [comment]
@fyookball Getting this on the latest with no multisig

**Comment by fyookball** [comment]
even with the latest patch that was merged? (run from source)
https://github.com/fyookball/electrum/commit/a2245ea0ee9ca152526a4ab5ac54971f5e2d3b35

this was done after 2.9.2 release
