### ISSUE TITLE
addrequest errors out with "not JSON serializable"

### ISSUE THREAD

**Issue by robbie0630** [fyookball/electrum#488]
Running Electron Cash 3.1.2 on Linux from the tarball on the website. After starting the daemon and loading the wallet, I try to run addrequest and get the following error:

```
$ ./electron-cash addrequest 3
Server-side error: <Fault -32603: Server error: File "/usr/lib/python3.5/json/encoder.py", line 179, in default | TypeError: b'\x8f\xd4\x04Wqs\xc4\x81!\x8b\xed\x11\nQ\x86\x14`\xe0\x02\xe1' is not JSON serializable
>
Traceback (most recent call last):
  File "/home/robbie/Electron Cash-3.1.2/packages/jsonrpclib/SimpleJSONRPCServer.py", line 447, in do_POST
    data, getattr(self, '_dispatch', None), self.path)
  File "/home/robbie/Electron Cash-3.1.2/packages/jsonrpclib/SimpleJSONRPCServer.py", line 268, in _marshaled_dispatch
    return jsonrpclib.jdumps(response, self.encoding)
  File "/home/robbie/Electron Cash-3.1.2/packages/jsonrpclib/jsonrpc.py", line 160, in jdumps
    return json.dumps(obj)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'\x8f\xd4\x04Wqs\xc4\x81!\x8b\xed\x11\nQ\x86\x14`\xe0\x02\xe1' is not JSON serializable
Traceback (most recent call last):
  File "./electron-cash", line 415, in <module>
    result = server.run_cmdline(config_options)
  File "/home/robbie/Electron Cash-3.1.2/packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/home/robbie/Electron Cash-3.1.2/packages/jsonrpclib/jsonrpc.py", line 531, in _request
    response = self._run_request(request)
  File "/home/robbie/Electron Cash-3.1.2/packages/jsonrpclib/jsonrpc.py", line 564, in _run_request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/robbie/Electron Cash-3.1.2/packages/jsonrpclib/jsonrpc.py", line 387, in single_request
    response.msg)
jsonrpclib.jsonrpc.ProtocolError: ('user:2z9n_BIe_OPQ0o4CGmdD5A==@127.0.0.1:7777/', 500, 'Internal Server Error', <http.client.HTTPMessage object at 0x7f5332959cf8>)
```

**Comment by kyuupichan** [comment]
I think that fixes it.  If you can test it would be good; re-open if there is still a problem.

**Comment by dbernt** [comment]
I had the same problem, tried the fix and it works.
