### ISSUE TITLE
Unable to create unsigned (payTo) transaction on testnet

### ISSUE THREAD

**Issue by johnconger** [fyookball/electrum#489]
1. Created a watch wallet using a public key by using:
`electron-cash restore -w Wallet.dat --testnet xpub6BsbTaAioD5rDYtV6jS7GcGJvk5cdvBQRPcuGJeWZY7dd6dx8Q4j4Fv5ff3KiYTfzBnhk1bPq7urDf4NJaxFesKFbgSA1fjUNjVgErnVvvS`

2. Funded address mxsChhTQuCMYoskd8eH4kV2YgvABqkdS7C from above wallet using faucet.
3. Started the daemon with: `electron-cash --testnet daemon start`
4. Loaded the wallet: `electron-cash --testnet daemon load_wallet -w Wallet.dat`
5. Ensured i had a balance:  `electron-cash --testnet getbalance -w Wallet.dat`
{  "confirmed": "13"  }
6. Tried to create an unsigned transaction using PayTo: 
`electron-cash  --testnet  payto mgRoeWs2CeCEuqQmNfhJjnpX8YvtPACmCX 1.1 --unsigned --fee 0.001 -w Wallet.dat`

    Traceback (most recent call last):
      File "/usr/local/bin/electron-cash", line 4, in <module>
        __import__('pkg_resources').run_script('Electron-Cash==3.1.2', 'electron-cash')
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
        exec(code, namespace, namespace)
      File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.2-py3.5.egg/EGG-INFO/scripts    /electron-cash", line 415, in <module>
        result = server.run_cmdline(config_options)
      File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 650, in __call__
        return self.__send(self.__name, args)
      File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 532, in _request
        check_for_errors(response)
      File "/usr/local/lib/python3.5/dist-packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
        raise ProtocolError((code, message))
    jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/local/lib/python3.5/dist-packages   /Electron_Cash-3.1.2-py3.5.egg/electroncash/transaction.py", line 493, in from_io | AssertionError\n')

**Comment by marceloneil** [comment]
I was able to reproduce this

**Comment by joware** [comment]
same issue here
