### ISSUE TITLE
Can't sign in cold-storage

### ISSUE THREAD

**Issue by kallerosenbaum** [fyookball/electrum#51]

**Comment by kallerosenbaum** [comment]
Created a transaction in a watch only wallet on an internet connected electron cash (2.9.0) and saved it to a USB stick. Then plugged it into an off-line computer to sign it with electron cash 2.9.0.

```Traceback (most recent call last):
  File "/home/kalle/Downloads/Electron Cash-2.9.0/gui/qt/util.py", line 582, in run
    result = task.task()
  File "/home/kalle/Downloads/Electron Cash-2.9.0/lib/wallet.py", line 1103, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/kalle/Downloads/Electron Cash-2.9.0/lib/keystore.py", line 113, in sign_transaction
    tx.sign(keypairs)
  File "/home/kalle/Downloads/Electron Cash-2.9.0/lib/transaction.py", line 828, in sign
    pre_hash = Hash(self.serialize_preimage(i).decode('hex'))
  File "/home/kalle/Downloads/Electron Cash-2.9.0/lib/transaction.py", line 726, in serialize_preimage
    amount = int_to_hex(txin['value'], 8)
KeyError: 'value'```

Could this be because electron cash doesn't have the value of the input at hand if it's in cold storage? Any workaround for this?

**Comment by fyookball** [comment]
should be fixed in next release or download latest code
