### ISSUE TITLE
Sweep function is broken in 3.1.2+

### ISSUE THREAD

**Issue by jyap808** [fyookball/electrum#510]
Error:

```
Server-side exception: <Fault -32603: Server error: File "[path]/Electron Cash-3.1.2/lib/transaction.py", line 493, in from_io | AssertionError
```

**Comment by fyookball** [comment]
steps to recreate?

**Comment by jyap808** [comment]
Full stack trace:
```Server-side exception: <Fault -32603: Server error: File "/MYPATH/Electron Cash-3.1.2/lib/transaction.py", line 493, in from_io | AssertionError
>
Traceback (most recent call last):
  File "/MYPATH/Electron Cash-3.1.2/packages/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/MYPATH/Electron Cash-3.1.2/lib/daemon.py", line 279, in run_cmdline
    result = func(*args, **kwargs)
  File "/MYPATH/Electron Cash-3.1.2/lib/commands.py", line 87, in func_wrapper
    return func(*args, **kwargs)
  File "/MYPATH/Electron Cash-3.1.2/lib/commands.py", line 398, in sweep
    tx = sweep(privkeys, self.network, self.config, destination, tx_fee, imax)
  File "/MYPATH/Electron Cash-3.1.2/lib/wallet.py", line 136, in sweep
    tx = Transaction.from_io(inputs, outputs)
  File "/MYPATH/Electron Cash-3.1.2/lib/transaction.py", line 493, in from_io
    for output in outputs)
AssertionError
Traceback (most recent call last):
  File "./electron-cash", line 415, in <module>
    result = server.run_cmdline(config_options)
  File "/MYPATH/Electron Cash-3.1.2/packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/MYPATH/Electron Cash-3.1.2/packages/jsonrpclib/jsonrpc.py", line 532, in _request
    check_for_errors(response)
  File "/MYPATH/Electron Cash-3.1.2/packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/MYPATH/Electron Cash-3.1.2/lib/transaction.py", line 493, in from_io | AssertionError\n')
```

**Comment by marceloneil** [comment]
Are you using this from the command line or the gui?

**Comment by jyap808** [comment]
Using command line

Electron-cash sweep privkey destaddy

**Comment by jyap808** [comment]
Running latest commit
```commit 5a83e351ce4a29538168eda5929845b778d23948
Author: Neil Booth <kyuupichan@gmail.com>
Date:   Sun Jan 21 22:14:16 2018 -0400

    Address tab: copy full address```

Error:
```Server-side exception: <Fault -32603: Server error: File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.3-py3.5.egg/electroncash/transaction.py", line 493, in from_io | AssertionError
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib_pelix-0.3.1-py3.5.egg/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.3-py3.5.egg/electroncash/daemon.py", line 279, in run_cmdline
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.3-py3.5.egg/electroncash/commands.py", line 88, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.3-py3.5.egg/electroncash/commands.py", line 399, in sweep
    tx = sweep(privkeys, self.network, self.config, destination, tx_fee, imax)
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.3-py3.5.egg/electroncash/wallet.py", line 136, in sweep
    tx = Transaction.from_io(inputs, outputs)
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.3-py3.5.egg/electroncash/transaction.py", line 493, in from_io
    for output in outputs)
AssertionError
Traceback (most recent call last):
  File "/usr/local/bin/electron-cash", line 4, in <module>
    __import__('pkg_resources').run_script('Electron-Cash==3.1.3', 'electron-cash')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.3-py3.5.egg/EGG-INFO/scripts/electron-cash", line 423, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib_pelix-0.3.1-py3.5.egg/jsonrpclib/jsonrpc.py", line 650, in __call__
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib_pelix-0.3.1-py3.5.egg/jsonrpclib/jsonrpc.py", line 532, in _request
  File "/usr/local/lib/python3.5/dist-packages/jsonrpclib_pelix-0.3.1-py3.5.egg/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.1.3-py3.5.egg/electroncash/transaction.py", line 493, in from_io | AssertionError\n')```

**Comment by jyap808** [comment]
@fyookball @marceloneil This is very easy to replicate. Running git head

System is Ubuntu 16 LTS 64-bit

run:
```
electron-cash sweep private_key destination
```

I can test any possible patches. Thanks

**Comment by jyap808** [comment]
Tested fine. Thanks all!
