### ISSUE TITLE
Ledger hardware wallet access on MacOS crashes Electron Cash

### ISSUE THREAD

**Issue by expatmt** [fyookball/electrum#515]
Trying to pair a fresh installation of the MacOS (10.13.3) build of Electron Cash (3.1.2) onto a Ledger Nano S. After selecting "Hardware Wallet" as the wallet type, the application crashes. Here's the console output:

```
default	15:09:08.452826 +0100	Console	[0x7fcdd80e8c00] Created session
default	15:09:08.453290 +0100	Console	[0x7fcdd80e8c00] Decoding: C0 0x002A0027 0x0006354A 0x11111100 0x00000000 766
default	15:09:08.453335 +0100	Console	[0x7fcdd80e8c00] Options: 42x39 [FFFFFFFF,FFFFFFFF] 0001D060
default	15:09:08.453401 +0100	Console	[0x7fcdd80e8c00] Decoding completed without errors
default	15:09:08.453576 +0100	Console	[0x7fcdd80e8c00] Releasing session
default	15:09:17.356621 +0100	CommCenter	#I handleLSNotitifcation_sync: Application launched: <private>
default	15:09:17.371008 +0100	mds	directQueryFetchResultsReply 225281 1795162112 35
default	15:09:17.372235 +0100	mds	directQueryFetchResultsReply 225283 1795162112 35
default	15:09:17.523161 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:17.544353 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:17.565979 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:17.586818 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:17.605993 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:17.627032 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:17.646468 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:17.667610 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:17.945154 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:17.951312 +0100	launchservicesd	CHECKIN:0x0-0x7c07c 9536 org.pythonmac.unspecified.Electron-Cash
default	15:09:17.959964 +0100	Electron-Cash	WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.3 instead of 10.13.3. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
default	15:09:17.960259 +0100	Electron-Cash	0   CarbonCore                          0x00007fff3bd443d8 ___Gestalt_SystemVersion_block_invoke + 112
default	15:09:17.960632 +0100	Electron-Cash	1   libdispatch.dylib                   0x00007fff624d9d50 _dispatch_client_callout + 8
default	15:09:17.960767 +0100	Electron-Cash	2   libdispatch.dylib                   0x00007fff624d9d03 dispatch_once_f + 41
default	15:09:17.960823 +0100	Electron-Cash	3   CarbonCore                          0x00007fff3bcd4da0 _Gestalt_SystemVersion + 948
default	15:09:17.960882 +0100	Electron-Cash	4   CarbonCore                          0x00007fff3bcd45e6 Gestalt + 139
default	15:09:17.960948 +0100	Electron-Cash	5   QtCore                              0x000000010684423c _ZN19QProcessEnvironment17systemEnvironmentEv + 35068
default	15:09:17.961059 +0100	Electron-Cash	6   QtCore                              0x0000000106825392 _ZN9QSettingsC1ERK7QStringS2_P7QObject + 34
default	15:09:17.982122 +0100	Console	LSExceptions shared instance invalidated for timeout.
default	15:09:17.997505 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:18.001969 +0100	Electron-Cash	MacOS error: -67050
default	15:09:18.905699 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	15:09:18.934591 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
error	15:09:19.135228 +0100	Electron-Cash	        AEGetDescData of non-desc type 'reco' not a good idea
default	15:09:19.146861 +0100	Electron-Cash	        OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(aevt,quit handler=0x105ccfff0 isSys=YES) err=-1717/errAEHandlerNotFound
default	15:09:19.146908 +0100	Electron-Cash	        OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(aevt,odoc handler=0x105ccfff0 isSys=YES) err=-1717/errAEHandlerNotFound
default	15:09:19.146938 +0100	Electron-Cash	        OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(GURL,GURL handler=0x105ccfff0 isSys=YES) err=0/noErr
default	15:09:25.457865 +0100	trustd	could not disable pinning: not an internal release
default	15:09:27.345317 +0100	Dock	LSExceptions shared instance invalidated for timeout.
default	15:09:28.854830 +0100	FinderExtension	-[FinderSync startHeartBeat]_block_invoke - Heartbeat START
default	15:09:28.854938 +0100	FinderExtension	-[FinderSync startHeartBeat]_block_invoke - Heartbeat FINISH
default	15:09:29.039638 +0100	Electron-Cash	LSExceptions shared instance invalidated for timeout.
default	15:09:29.529416 +0100	Electron-Cash	Electron-Cash Error
default	15:09:32.454036 +0100	CommCenter	#I handleLSNotitifcation_sync: Application exited: <private>
```

**Comment by marceloneil** [comment]
@expatmt can you try running:
```
/Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash -v
```
That should give us a bit more information

**Comment by expatmt** [comment]
@marceloneil - right here, sir:

```
iain@apollo ~ $ /Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash -v
[SimpleConfig] electron-cash directory /Users/iain/.electron-cash
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', u'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', u'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', u'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', u'TREZOR wallet')
[profiler] __init__ 0.0124
[Network] blockchains [0]
[Network] starting network
[Network] connecting to mash.1209k.com:50002:s as new interface
[FxThread] using exchange Kraken
[mash.1209k.com] cannot resolve hostname
[electrumx-cash.1209k.com] cannot resolve hostname
[electroncash.cascharia.com] connected
[bch.tedy.pw] connected
[abc.vom-stausee.de] connected
[electrumx-bch.adminsehow.com] connected
[Network] switching to abc.vom-stausee.de:52002:s
[Network] sending subscriptions to abc.vom-stausee.de:52002:s 0 0
[Network] fee_estimates[25] 1023
[Network] fee_estimates[10] 1144
[Network] fee_estimates[5] 1144
[Network] fee_estimates[2] 1144
[Network] relayfee 1000
[abc.vom-stausee.de] binary search
[bch.tedy.pw] binary search
[electroncash.cascharia.com] binary search
[electrumx-bch.adminsehow.com] binary search
[electroncash.checksum0.com] connected
[bch.curalle.ovh] connected
[electroncash.bitcoinplug.com] connected
[electrum.leblancnet.us] SSL certificate signed by CA
[electrum.leblancnet.us] connected
[bch.curalle.ovh] binary search
[electron-cash.dragon.zone] SSL error retrieving SSL certificate: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:661)
[electroncash.checksum0.com] binary search
[electroncash.bitcoinplug.com] binary search
[WalletStorage] wallet path /Users/iain/.electron-cash/wallets/default_wallet
[WalletStorage] wallet path /Users/iain/.electron-cash/wallets/default_wallet
[electrum.leblancnet.us] binary search
[bch.tedy.pw] catching up from 44352
[bch.tedy.pw] requesting chunk 22
[WalletStorage] wallet path /Users/iain/.electron-cash/wallets/default_wallet
[bitcoincash.is-by.us] SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
[bch.tedy.pw] requesting chunk 23
[electroncash.cascharia.com] binary search
[crypto.mldlabs.com] SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
[bch.tedy.pw] requesting chunk 24
[electrumx-bch.adminsehow.com] binary search
[abc1.hsmiths.com] connected
[bch.tedy.pw] requesting chunk 25
[electron.ueo.ch] failed to connect timed out
[bch.tedy.pw] requesting chunk 26
[abc1.hsmiths.com] binary search
[bch.tedy.pw] requesting chunk 27
[electroncash.bitcoinplug.com] {'method': 'blockchain.block.get_header', u'jsonrpc': u'2.0', u'id': 206, 'params': [50718], u'error': {u'message': u'internal error processing request', u'code': -32603}}
Traceback (most recent call last):
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/plugins.py", line 150, in get_hardware_support
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/plugins.py", line 178, in get_plugin
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/plugins.py", line 102, in load_plugin
  File "pkgutil.pyc", line 246, in load_module
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/plugins/digitalbitbox/qt.py", line 1, in <module>
ImportError: cannot import name QInputDialog
[Plugins] cannot load plugin for: digitalbitbox
[Plugins] loaded trezor
Traceback (most recent call last):
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/plugins.py", line 150, in get_hardware_support
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/plugins.py", line 178, in get_plugin
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/plugins.py", line 102, in load_plugin
  File "pkgutil.pyc", line 246, in load_module
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/plugins/ledger/qt.py", line 12, in <module>
ImportError: No module named btchip.btchipPersoWizard
[Plugins] cannot load plugin for: ledger
[Plugins] loaded keepkey
Traceback (most recent call last):
  File "/Applications/Electron-Cash.app/Contents/Resources/__boot__.py", line 98, in <module>
    _run()
  File "/Applications/Electron-Cash.app/Contents/Resources/__boot__.py", line 82, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/Electron-Cash.app/Contents/Resources/electron-cash.py", line 373, in <module>
    d.init_gui(config, plugins)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/daemon.py", line 283, in init_gui
    self.gui.main()
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/gui/qt/__init__.py", line 215, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/gui/qt/__init__.py", line 175, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/gui/qt/installwizard.py", line 268, in run_and_get_wallet
    self.run(action)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/base_wizard.py", line 60, in run
    f(*args)
[electron.coinucopia.io] saving certificate
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/base_wizard.py", line 86, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/gui/qt/installwizard.py", line 89, in func_wrapper
[electron.coinucopia.io] connected
    run_next(*out)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/base_wizard.py", line 96, in on_wallet_type
    self.run(action)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/base_wizard.py", line 60, in run
    f(*args)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/base_wizard.py", line 128, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/gui/qt/installwizard.py", line 89, in func_wrapper
    run_next(*out)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/base_wizard.py", line 60, in run
    f(*args)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/lib/base_wizard.py", line 170, in choose_hw_device
    self.confirm_dialog(title=title, message=msg, run_next= lambda x: self.choose_hw_device())
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/gui/qt/installwizard.py", line 79, in func_wrapper
    out = func(*args, **kwargs)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/gui/qt/installwizard.py", line 419, in confirm_dialog
    self.confirm(message, title)
  File "/Applications/Electron-Cash.app/Contents/Resources/lib/python2.7/gui/qt/installwizard.py", line 424, in confirm
    vbox.addWidget(WWLable(message))
NameError: global name 'WWLable' is not defined
2018-01-27 11:08:06.077 Electron-Cash[10074:2428941] Electron-Cash Error
[Daemon] shutting down network
[Plugins] stopped
[electron.villocq.com] saving certificate
[electron.villocq.com] connected
[bch.tedy.pw] requesting chunk 28
[Network] stopping network
[Network] stopped
[Daemon] stopped
```

**Comment by fyookball** [comment]
why's it saying python2.7 ?

**Comment by expatmt** [comment]
NFI. I simply downloaded and ran the binary. If it helps:

```
iain@apollo ~ $ python
python             python2.7-config   python3.6m
python-config      python3            python3.6m-config
python2            python3-config     pythonw
python2-config     python3.6          pythonw2
python2.7          python3.6-config   pythonw2.7
iain@apollo ~ $ ls -l /usr/bin/python
-rwxr-xr-x  1 root  wheel  66880 Oct 25 18:37 /usr/bin/python
```

**Comment by marceloneil** [comment]
That's very odd. It's working find on my MacOS vm. Are you sure that you are running 3.1.2 from https://electroncash.org? Try running this:
```
ls /Applications/Electron-Cash.app/Contents/Resources/lib
```
You should get:
```
python3.6        python36.zip
```

**Comment by expatmt** [comment]
Downloaded the `dmg` directly from the website. Interestingly enough...

```
iain@apollo ~ $ ls /Applications/Electron-Cash.app/Contents/Resources/lib
python2.7
```

Removed the application and performed a clean reinstall. Now I get:

```
iain@apollo ~ $ ls /Applications/Electron-Cash.app/Contents/Resources/lib
python3.6	python36.zip
```

And it's all working. Guessing there must have still been an older version lying about the place. I put it down to user error. ;)

Thank you and apologies for the trouble.

**Comment by marceloneil** [comment]
Glad you got it working :)
