### ISSUE TITLE
listaddresses error

### ISSUE THREAD

**Issue by corper** [fyookball/electrum#539]
I run electron-cash 3.1.2 daemon in centos 7. I run command "./electron-cash listaddresses" After create and load a wallet. Then the errors are showed below:
```
Server-side error: <Fault -32603: Server error: File "/usr/lib64/python3.6/json/encoder.py", line 180, in default | TypeError: Object of type 'bytes' is not JSON serializable
>
Traceback (most recent call last):
  File "/root/electron-cash/packages/jsonrpclib/SimpleJSONRPCServer.py", line 447, in do_POST
    data, getattr(self, '_dispatch', None), self.path)
  File "/root/electron-cash/packages/jsonrpclib/SimpleJSONRPCServer.py", line 268, in _marshaled_dispatch
    return jsonrpclib.jdumps(response, self.encoding)
  File "/root/electron-cash/packages/jsonrpclib/jsonrpc.py", line 160, in jdumps
    return json.dumps(obj)
  File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
Traceback (most recent call last):
  File "./electron-cash", line 415, in <module>
    result = server.run_cmdline(config_options)
  File "/root/electron-cash/packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/root/electron-cash/packages/jsonrpclib/jsonrpc.py", line 531, in _request
    response = self._run_request(request)
  File "/root/electron-cash/packages/jsonrpclib/jsonrpc.py", line 564, in _run_request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/root/electron-cash/packages/jsonrpclib/jsonrpc.py", line 387, in single_request
    response.msg)
jsonrpclib.jsonrpc.ProtocolError: ('user:xxxx@127.0.0.1:7777/', 500, 'Internal Server Error', <http.client.HTTPMessage object at 0x7f523a859be0>)
```

**Comment by corper** [comment]
Here is more info from daemon:

{'id': '1e9d84d8-60ce-4559-bc4f-9dd3320e1233', 'result': [[b'\xca\xcfUq,\x99\x1fb\xc2\xbe\xf6\xac})\xb9-W\xa7\x83\x9a', 0], [b'\x90o) \x9dO\x13A\x954\xf7\x9e>\x80\xd8G\x8f\x91\xc6\xbc', 0], [b'8\xcd\x84u{qf\xea\xda K\x1c\x96\xad\xcf\x834R\xce\xc2', 0], [b"\tn\x0e\xb3\x08\x98'?OD\x12UF\x04\x9bYh\xc7V\xf4", 0], [b'O\x9f\x8fO\xf6\xfa)u\xaa\x00\x89\x12\xb6;\xea\x0b\x90\x16p=', 0], [b'r\xa32DX\x9e\x85\x7f;[U\x9dug\x85K\x04SCq', 0], [b'\xb0\x97\xe7\xc9\xc3;wj\x1aKo\xe7X\x828V\xb1c\xc2H', 0], [b'\x8e\xaa\xb4~\x83\xd1\xbd>\xa20\x89\xe1\xa2\x1e\x8eZ\xfc^/\xff', 0], [b"'\x87N\xf3\xab\xb1g\xa3\xe1\x9f\x95\xdf'\x16t\xa4\xcd\xbbmL", 0], [b'\xf9?4\x913\xb5\xd0\x9f\xa29\xff\xb8\xfd\x1c\xc0\xbf<\xc5\xf7\xa8', 0], [b'\xfd\xe0\xe1\xf9\xe4\xb7-w\xb9\xa3\xd0\x98\xef\xef\x80$a\x08\xc4d', 0], [b'w \x10\x06\xb1;\x14\xbdv\xe3\x97\x08^p\xa9\xc3\xb3,\x02\xa8', 0], [b'\xa2?\xca(\xed!\x88\xd5ak\xe1\x91{\x8c\x06C\xa4+\xa3%', 0], [b'Pa\xdfb!;|1_\t%uX-\xc4\xef_\xe1pj', 0], [b"\xa1\x12\x00\xa3\xf4\xfd%\xc9\xe9\xd5d\x97\xf6^|3\x8a'\x9c\xc5", 0], [b'\x87\xec\xedy\xfa\xa05F<;D>\x165\xf7\xc68\xbc\xdfc', 0], [b"`\xd22\x9e\x951b\xc9#S~\x1a\xc9\x82\xc1~\xd7'@O", 0], [b"\xae\xc2\xf4\x14\xa5\xb9\x93\xa0'v=\xdan\x92\x87\xdbd\xb8!8", 0], [b'K\x14\xcd\xfdz\xcd\xf6mBmGZ\x9b\x1d61>\xce;\x8e', 0], [b'\xf7\x17\xa2\xe5[\xf1t\xdb\xb5\xc3M@\x82\x1cj\x91y\xea!\x9e', 0], [b'\x1b\x91.\xc8\x90\x92]\x82E\xaf\x17\x15b\xb5\xa7(\x14\x96\xd5\xc1', 0], [b'\x0bji=\xb3m\x1b \xc7\xcf\x8d\xf2q\xa8\xc2~HL\x9fB', 0], [b'\x03\xf5\xb4\x12\x0b6\xe8\xf8\x81\xe3l\x1c\xd1K$|\xc3\x8b\xae\xee', 0], [b"\x97\x18\xe2\xd4)'D7\x98\xaa\\\xe49>\xa7y\xa1\xd65\xb9", 0], [b's\x01\xc9\xf88\n\xc8\x82\x05\xbf\x0e\xb4\xdd\xd4U\xddTc\x0f\x01', 0], [b'\xbe\xf8\x95}Q\xb2L\x1b\xb6h\xa1c+\x00\x92\xe0\x93\n\x03\xb1', 0]], 'jsonrpc': '2.0'}
Server-side error: <Fault -32603: Server error: File "/usr/lib/python3.5/json/encoder.py", line 179, in default | TypeError: b'\xca\xcfUq,\x99\x1fb\xc2\xbe\xf6\xac})\xb9-W\xa7\x83\x9a' is not JSON serializable
>
Traceback (most recent call last):
  File "/root/electroncash/Electron Cash-3.1.2/packages/jsonrpclib/SimpleJSONRPCServer.py", line 448, in do_POST
    data, getattr(self, '_dispatch', None), self.path)
  File "/root/electroncash/Electron Cash-3.1.2/packages/jsonrpclib/SimpleJSONRPCServer.py", line 269, in _marshaled_dispatch
    return jsonrpclib.jdumps(response, self.encoding)
  File "/root/electroncash/Electron Cash-3.1.2/packages/jsonrpclib/jsonrpc.py", line 160, in jdumps
    return json.dumps(obj)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'\xca\xcfUq,\x99\x1fb\xc2\xbe\xf6\xac})\xb9-W\xa7\x83\x9a' is not JSON serializable

I think the format of addresses are wrong. They can't to be change to JSON format.

**Comment by corper** [comment]
I found the bug:

in listaddresses of Commands class, the addr is a instance of Address class but not a string and jsonrpclib.dump can't parse Address instance to json string.

**Comment by neyromanser** [comment]
Also noticed that with daemon disabled listaddresses works without error

**Comment by corper** [comment]
All the commands related to Address class have the same bug.
