### ISSUE TITLE
command "payto" error

### ISSUE THREAD

**Issue by corper** [fyookball/electrum#549]
version: 3.1.2
The error messages: 
>Server-side exception: <Fault -32603: Server error: File "/root/electron-cash/lib/transaction.py", line 493, in from_io | AssertionError
>\>
Traceback (most recent call last):
  File "/root/electron-cash/packages/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/root/electron-cash/lib/daemon.py", line 279, in run_cmdline
    result = func(*args, **kwargs)
  File "/root/electron-cash/lib/commands.py", line 88, in func_wrapper
    return func(*args, **kwargs)
  File "/root/electron-cash/lib/commands.py", line 441, in payto
    tx = self._mktx([(destination, amount)], tx_fee, change_addr, domain, nocheck, unsigned, password, locktime)
  File "/root/electron-cash/lib/commands.py", line 428, in _mktx
    tx = self.wallet.make_unsigned_transaction(coins, final_outputs, self.config, fee, change_addr)
  File "/root/electron-cash/lib/wallet.py", line 927, in make_unsigned_transaction
    fee_estimator, self.dust_threshold())
  File "/root/electron-cash/lib/coinchooser.py", line 180, in make_tx
    tx = Transaction.from_io([], outputs)
  File "/root/electron-cash/lib/transaction.py", line 493, in from_io
    for output in outputs)

The bug is in ```_mktx``` method of ```Commands``` class in commands.py file. I fixed the bug in my computer by changing the line
```final_outputs.append((TYPE_ADDRESS, address, amount))```
to
```final_outputs.append((TYPE_ADDRESS, Address.from_string(address), amount))```

This is another one of the "Address" class related bugs when using command.

**Comment by marceloneil** [comment]
This seems like a duplicate of #489, have you tried running it from git head?

**Comment by corper** [comment]
Yes. It's duplicate. Thank you.

**Comment by marceloneil** [comment]
No problem :)
