### ISSUE TITLE
KeyError: 'value' when trying to sign tx on offline (cold storage) ubuntu 14.04 machine

### ISSUE THREAD

**Issue by SimonVrouwe** [fyookball/electrum#57]
On an online ubuntu 14.04 machine, I run ./electrum-cash directly from folder, then I did the following:
1. Create a watch-only wallet and import a pubkey
2. Create unsigned tx from the watch-only wallet to a bitcoin-cash address and save tx on USB stick
3. On another offline ubuntu 14.04 machine, run ./electrum-cash and create a new wallet and import the private key that belongs to the pubkey used in the tx
4. Load the unsigned tx from USB and sign

Doing that with GUI gives short error message: Error 'value'
When I try directly from command line using something like this: 
cat unsigned.txn | ./electron-cash signtransaction - > signed.txn

Then following error message:
Traceback (most recent call last):
  File "./electron-cash", line 427, in <module>
    result = run_offline_command(config, config_options)
  File "./electron-cash", line 286, in run_offline_command
    result = func(*args)
  File "/home/simon/bcash/Electron Cash-2.9.0/lib/commands.py", line 83, in func_wrapper
    return func(*args, **kwargs)
  File "/home/simon/bcash/Electron Cash-2.9.0/lib/commands.py", line 239, in signtransaction
    self.wallet.sign_transaction(tx, password)
  File "/home/simon/bcash/Electron Cash-2.9.0/lib/wallet.py", line 1103, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/simon/bcash/Electron Cash-2.9.0/lib/keystore.py", line 113, in sign_transaction
    tx.sign(keypairs)
  File "/home/simon/bcash/Electron Cash-2.9.0/lib/transaction.py", line 828, in sign
    pre_hash = Hash(self.serialize_preimage(i).decode('hex'))
  File "/home/simon/bcash/Electron Cash-2.9.0/lib/transaction.py", line 726, in serialize_preimage
    amount = int_to_hex(txin['value'], 8)
KeyError: 'value'

**Comment by fyookball** [comment]
try with latest 2.9.2

**Comment by SimonVrouwe** [comment]
Yes is working now, thanks!
