### ISSUE TITLE
createnewaddress command error

### ISSUE THREAD

**Issue by corper** [fyookball/electrum#587]
version: 3.1.5
> Server-side error: <Fault -32603: Server error: File "/usr/lib64/python3.6/json/encoder.py", line 180, in default | TypeError: Object of type 'bytes' is not JSON serializable
\>
Traceback (most recent call last):
  File "/root/Electron Cash-3.1.5/packages/jsonrpclib/SimpleJSONRPCServer.py", line 448, in do_POST
    data, getattr(self, '_dispatch', None), self.path)
  File "/root/Electron Cash-3.1.5/packages/jsonrpclib/SimpleJSONRPCServer.py", line 269, in _marshaled_dispatch
    return jsonrpclib.jdumps(response, self.encoding)
  File "/root/Electron Cash-3.1.5/packages/jsonrpclib/jsonrpc.py", line 160, in jdumps
    return json.dumps(obj)
  File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
^CTraceback (most recent call last):
  File "./electron-cash", line 419, in <module>
    d.join()
  File "/usr/lib64/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

createnewaddress method of commands.py should return a string. I fixed it in this way:
change ```return self.wallet.create_new_address(False)```
to ```return str(self.wallet.create_new_address(False))```

**Comment by patrick99e99** [comment]
+1

**Comment by patrick99e99** [comment]
why was this closed?
