### ISSUE TITLE
Crashes when creating new wallet

### ISSUE THREAD

**Issue by WishfulThinking** [fyookball/electrum#592]
```
Traceback (most recent call last):
  File "/usr/local/bin/electron-cash", line 373, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/share/electron-cash/lib/daemon.py", line 304, in init_gui
    self.gui.main()
  File "/usr/local/share/electron-cash/gui/qt/__init__.py", line 251, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/local/share/electron-cash/gui/qt/__init__.py", line 210, in start_n                                 ew_window
    wallet.start_threads(self.daemon.network)
  File "/usr/local/share/electron-cash/lib/wallet.py", line 996, in start_threads
    self.synchronizer = Synchronizer(self, network)
  File "/usr/local/share/electron-cash/lib/synchronizer.py", line 55, in __init__
    self.initialize()
  File "/usr/local/share/electron-cash/lib/synchronizer.py", line 186, in initialize
    self.subscribe_to_addresses(self.wallet.get_addresses())
  File "/usr/local/share/electron-cash/lib/synchronizer.py", line 76, in subscri                                 be_to_addresses
    hashes = [addr.to_scripthash_hex() for addr in addresses]
  File "/usr/local/share/electron-cash/lib/synchronizer.py", line 76, in <listcomp>
    hashes = [addr.to_scripthash_hex() for addr in addresses]
  File "/usr/local/share/electron-cash/lib/address.py", line 440, in to_scriptha                                 sh_hex
    return hash_to_hex_str(self.to_scripthash())
  File "/usr/local/share/electron-cash/lib/address.py", line 80, in hash_to_hex_str
    return bytes(reversed(x)).hex()
AttributeError: 'bytes' object has no attribute 'hex'
```

**Comment by marceloneil** [comment]
Duplicate of #420
