### ISSUE TITLE
deserialize fails

### ISSUE THREAD

**Issue by awemany** [fyookball/electrum#638]
Hi, 

the `deserialize` cmd does not seem to work for me. I started an `electron-cash` daemon as well as an `electrum` one. Electrum 3.1.2. can decode the BCH txn, though electron-cash can't. Here's my console interaction to try to decode a recent coinbase txn:
```
awemany@bitcoinunlimited:~/Electron Cash-3.1.6$ ./electron-cash gettransaction 147f8cff3bb64a78bd97a947cb90734c9ee4aed9002aa026f98fb39379797bfa{
    "complete": true,
    "final": true,
    "hex": "01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff2503020608184d696e656420627920416e74506f6f6c343505205ad1f03ede83000063f70100ffffffff0209e9954a000000001976a9141fefe863a7e0ddc767780ce3bedc564cf5cbda6388acfcc80200000000001976a914000000000000000000000000000000000000000088ac00000000"
}
awemany@bitcoinunlimited:~/Electron Cash-3.1.6$ ./electron-cash deserialize 01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff2503020608184d696e656420627920416e74506f6f6c343505205ad1f03ede83000063f70100ffffffff0209e9954a000000001976a9141fefe863a7e0ddc767780ce3bedc564cf5cbda6388acfcc80200000000001976a914000000000000000000000000000000000000000088ac00000000
Server-side error: <Fault -32603: Server error: File "/usr/lib/python3.6/json/encoder.py", line 180, in default | TypeError: Object of type 'bytes' is not JSON serializable
>
Traceback (most recent call last):
  File "/home/awemany/Electron Cash-3.1.6/packages/jsonrpclib/SimpleJSONRPCServer.py", line 447, in do_POST
    data, getattr(self, '_dispatch', None), self.path)
  File "/home/awemany/Electron Cash-3.1.6/packages/jsonrpclib/SimpleJSONRPCServer.py", line 268, in _marshaled_dispatch
    return jsonrpclib.jdumps(response, self.encoding)
  File "/home/awemany/Electron Cash-3.1.6/packages/jsonrpclib/jsonrpc.py", line 160, in jdumps
    return json.dumps(obj)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
Traceback (most recent call last):
  File "./electron-cash", line 435, in <module>
    result = server.run_cmdline(config_options)
  File "/home/awemany/Electron Cash-3.1.6/packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/home/awemany/Electron Cash-3.1.6/packages/jsonrpclib/jsonrpc.py", line 531, in _request
    response = self._run_request(request)
  File "/home/awemany/Electron Cash-3.1.6/packages/jsonrpclib/jsonrpc.py", line 564, in _run_request
    verbose=self.__verbose
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/awemany/Electron Cash-3.1.6/packages/jsonrpclib/jsonrpc.py", line 387, in single_request
    response.msg)
jsonrpclib.jsonrpc.ProtocolError: ('user:XXX@127.0.0.1:34825/', 500, 'Internal Server Error', <http.client.HTTPMessage object at 0x7f650ead0048>)
awemany@bitcoinunlimited:~/Electron Cash-3.1.6$ electrum deserialize 01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff2503020608184d696e656420627920416e74506f6f6c343505205ad1f03ede83000063f70100ffffffff0209e9954a000000001976a9141fefe863a7e0ddc767780ce3bedc564cf5cbda6388acfcc80200000000001976a914000000000000000000000000000000000000000088ac00000000
{
    "inputs": [
        {
            "address": null,
            "num_sig": 0,
            "prevout_hash": "0000000000000000000000000000000000000000000000000000000000000000",
            "prevout_n": 4294967295,
            "pubkeys": [],
            "scriptSig": "03020608184d696e656420627920416e74506f6f6c343505205ad1f03ede83000063f70100",
            "sequence": 4294967295,
            "signatures": {},
            "type": "coinbase",
            "x_pubkeys": []
        }
    ],
    "lockTime": 0,
    "outputs": [
        {
            "address": "13usM2ns3f466LP65EY1h8hnTBLFiJV6rD",
            "prevout_n": 0,
            "scriptPubKey": "76a9141fefe863a7e0ddc767780ce3bedc564cf5cbda6388ac",
            "type": 0,
            "value": 1251338505
        },
        {
            "address": "1111111111111111111114oLvT2",
            "prevout_n": 1,
            "scriptPubKey": "76a914000000000000000000000000000000000000000088ac",
            "type": 0,
            "value": 182524
        }
    ],
    "version": 1
}```

**Comment by rt121212121** [comment]
@fyookball The command that errors above in 3.1.2, now works with the latest code. This can be closed.

**Comment by qr1qr1** [comment]
Hi,
I have the same error. Can anyone help?
I tried on Python 3.6.5 and 3.5.6 but with no success:

Python 3.6.5:
`
Server-side error: <Fault -32603: Server error: File "/usr/lib64/python3.6/json/encoder.py", line 180, in default | TypeError: Object of type 'bytes' is not JSON serializable
>
Traceback (most recent call last):
  File "packages/jsonrpclib/SimpleJSONRPCServer.py", line 447, in do_POST
    data, getattr(self, '_dispatch', None), self.path)
  File "packages/jsonrpclib/SimpleJSONRPCServer.py", line 268, in _marshaled_dispatch
    return jsonrpclib.jdumps(response, self.encoding)
  File "packages/jsonrpclib/jsonrpc.py", line 160, in jdumps
    return json.dumps(obj)
  File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
`
Python 3.5.6:
`
Server-side error: <Fault -32603: Server error: File "/usr/local/lib/python3.5/json/encoder.py", line 179, in default | TypeError: b'\xc7`h\xa7\x10/B\x98\xd5\xac\xe9\x0e\xc6\xf4\x82%]\x8e\x85\xf0' is not JSON serializable
>
Traceback (most recent call last):
  File "packages/jsonrpclib/SimpleJSONRPCServer.py", line 447, in do_POST
    data, getattr(self, '_dispatch', None), self.path)
  File "packages/jsonrpclib/SimpleJSONRPCServer.py", line 268, in _marshaled_dispatch
    return jsonrpclib.jdumps(response, self.encoding)
  File "packages/jsonrpclib/jsonrpc.py", line 160, in jdumps
    return json.dumps(obj)
  File "/usr/local/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'\xc7`h\xa7\x10/B\x98\xd5\xac\xe9\x0e\xc6\xf4\x82%]\x8e\x85\xf0' is not JSON serializable`

**Comment by cculianu** [comment]
@qr1qr1 did you get here from a google search? This is the issue tracker for electron cash, not for generic python support.  JSON doesn't support byte arrays.  You need to explicitly decode byte arrays to strings or some other encoding scheme to serialize them using JSON.

**Comment by qr1qr1** [comment]
Hi @cculianu 
This is from "electron-cash deserialize" command:
```
$ electron-cash gettransaction 23a543c642b352734ab501296aee7f76dc6a73ca3d601147ef582dedfba52c49
{
    "complete": true,
    "final": true,
    "hex": "0200000001abb51d5412b5a0762824deef3de7174ba31273b66451c3fce86807d5d3cf4a70000000006b483045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41210378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980feffffff0203076500000000001976a914c76068a7102f4298d5ace90ec6f482255d8e85f088ac979c2f00000000001976a9143231991e6d9a4e9beea696dee2e1e450389421d588ac8a4f0800"
}

$ electron-cash deserialize 0200000001abb51d5412b5a0762824deef3de7174ba31273b66451c3fce86807d5d3cf4a70000000006b483045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41210378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980feffffff0203076500000000001976a914c76068a7102f4298d5ace90ec6f482255d8e85f088ac979c2f00000000001976a9143231991e6d9a4e9beea696dee2e1e450389421d588ac8a4f0800
Traceback (most recent call last):
  File "electron-cash", line 437, in <module>
    result = server.run_cmdline(config_options)
  File "packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "packages/jsonrpclib/jsonrpc.py", line 531, in _request
    response = self._run_request(request)
  File "packages/jsonrpclib/jsonrpc.py", line 564, in _run_request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "packages/jsonrpclib/jsonrpc.py", line 387, in single_request
    response.msg)
```
Does deserialize work for you?

**Comment by cculianu** [comment]
Oh sorry. All apologies.  Didn't read the stack trace properly.  This works in the latest release.

On Mac: 

```
 /Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash deserialize 0200000001abb51d5412b5a0762824deef3de7174ba31273b66451c3fce86807d5d3cf4a70000000006b483045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41210378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980feffffff0203076500000000001976a914c76068a7102f4298d5ace90ec6f482255d8e85f088ac979c2f00000000001976a9143231991e6d9a4e9beea696dee2e1e450389421d588ac8a4f0800
{'version': 2, 'inputs': [{'prevout_hash': '704acfd3d50768e8fcc35164b67312a34b17e73defde242876a0b512541db5ab', 'prevout_n': 0, 'sequence': 4294967294, 'address': <Address qre3tww9gyru8k9a2lnju47a9khay9ezc530ngekem>, 'x_pubkeys': ['0378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980'], 'pubkeys': ['0378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980'], 'signatures': ['3045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41'], 'type': 'p2pkh', 'num_sig': 1, 'scriptSig': '483045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41210378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980'}], 'outputs': [{'value': 6620931, 'type': 0, 'address': <Address qrrkq698zqh59xx44n5sa3h5sgj4mr597qgch8985d>, 'scriptPubKey': '76a914c76068a7102f4298d5ace90ec6f482255d8e85f088ac', 'prevout_n': 0}, {'value': 3120279, 'type': 0, 'address': <Address qqerrxg7dkdyaxlw56tdachpu3gr39pp65luxhnshp>, 'scriptPubKey': '76a9143231991e6d9a4e9beea696dee2e1e450389421d588ac', 'prevout_n': 1}], 'lockTime': 544650}
```

On Linux:

```
./electron-cash deserialize 0200000001abb51d5412b5a0762824deef3de7174ba31273b66451c3fce86807d5d3cf4a70000000006b483045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41210378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980feffffff0203076500000000001976a914c76068a7102f4298d5ace90ec6f482255d8e85f088ac979c2f00000000001976a9143231991e6d9a4e9beea696dee2e1e450389421d588ac8a4f0800
{'outputs': [{'type': 0, 'scriptPubKey': '76a914c76068a7102f4298d5ace90ec6f482255d8e85f088ac', 'value': 6620931, 'address': <Address qrrkq698zqh59xx44n5sa3h5sgj4mr597qgch8985d>, 'prevout_n': 0}, {'type': 0, 'scriptPubKey': '76a9143231991e6d9a4e9beea696dee2e1e450389421d588ac', 'value': 3120279, 'address': <Address qqerrxg7dkdyaxlw56tdachpu3gr39pp65luxhnshp>, 'prevout_n': 1}], 'version': 2, 'inputs': [{'num_sig': 1, 'pubkeys': ['0378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980'], 'scriptSig': '483045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41210378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980', 'signatures': ['3045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41'], 'type': 'p2pkh', 'prevout_hash': '704acfd3d50768e8fcc35164b67312a34b17e73defde242876a0b512541db5ab', 'prevout_n': 0, 'x_pubkeys': ['0378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980'], 'sequence': 4294967294, 'address': <Address qre3tww9gyru8k9a2lnju47a9khay9ezc530ngekem>}], 'lockTime': 544650}
```

I think upgrade to latest release and/or github?

**Comment by qr1qr1** [comment]
I tested on ElectronCash-3.3.1. Which version do you have?

**Comment by cculianu** [comment]
Same!  3.3.1.  Whaaa??!?!

How can this be?!  I swear it totally works for me! 

What's different here?  This is bizarre.

You're on Ubuntu? Or?

**Comment by qr1qr1** [comment]
Centos 7.
I tried on Python 3.5.6 and 3.6.5
What Python version do you have?

**Comment by cculianu** [comment]
I'm on Ubuntu 17.   Python 3.6.3 but I don't think the python version should matter much because the JSON RPC stuff didn't change THAT radically between python versions. Did it? (I also tried it on my Mac system from source  -- I got Python 3.5 installled on that one and it worked fine).

Here is the output from my Ubuntu:

```
calin@calin-ubuntu17:~/tmp/ec$ python3 --version
Python 3.6.3
calin@calin-ubuntu17:~/tmp/ec$ ./electron-cash deserialize 0200000001abb51d5412b5a0762824deef3de7174ba31273b66451c3fce86807d5d3cf4a70000000006b483045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41210378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980feffffff0203076500000000001976a914c76068a7102f4298d5ace90ec6f482255d8e85f088ac979c2f00000000001976a9143231991e6d9a4e9beea696dee2e1e450389421d588ac8a4f0800
{'version': 2, 'inputs': [{'prevout_hash': '704acfd3d50768e8fcc35164b67312a34b17e73defde242876a0b512541db5ab', 'prevout_n': 0, 'sequence': 4294967294, 'address': <Address qre3tww9gyru8k9a2lnju47a9khay9ezc530ngekem>, 'x_pubkeys': ['0378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980'], 'pubkeys': ['0378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980'], 'signatures': ['3045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41'], 'type': 'p2pkh', 'num_sig': 1, 'scriptSig': '483045052100e2086ec91dd3d2735357151dd565df10f6d41ba4fbb9bc00e2494729191a49b702204fbb145b8409a473ad7fb329db296755f47c0c56e4ed1951a9708bf84c0efe8e41210378422101596d3300a5a18d8d12aeab22df46ffa90874c40dd46a52152c54e980'}], 'outputs': [{'value': 6620931, 'type': 0, 'address': <Address qrrkq698zqh59xx44n5sa3h5sgj4mr597qgch8985d>, 'scriptPubKey': '76a914c76068a7102f4298d5ace90ec6f482255d8e85f088ac', 'prevout_n': 0}, {'value': 3120279, 'type': 0, 'address': <Address qqerrxg7dkdyaxlw56tdachpu3gr39pp65luxhnshp>, 'scriptPubKey': '76a9143231991e6d9a4e9beea696dee2e1e450389421d588ac', 'prevout_n': 1}], 'lockTime': 544650}
```

**Comment by qr1qr1** [comment]
Thanks ccoulianu for the information. I will try on different OS.

**Comment by cculianu** [comment]
You're welcome.  This is perplexing tho. So bizarre! :)

I suspect you may have a broken or weird jsonrpclib or some other python package.. but just a hunch.  Could be anything.  Good luck!!

**Comment by qr1qr1** [comment]
When I run `./electron-cash daemon start` and later `deserialize` then it doesn't work.
When the daemon is stopped it works.
It seems when the daemon is running then the command is passed through json rpc.
Could you cculianu try to run `deserialize` with daemon on?

**Comment by cculianu** [comment]
Yeah ok the problem is the stuff in the tx dict contains classes such as 'Address' and 'ScriptOutput' which are tuples which contain bytes arrays.  

JSON sees tuples and it just iterates through each element and dumps it.

But those classes contain bytes objects.

I know how to fix this .. I think. Basically I have to figure out if JSON lets me inherit from some API to override how it encodes namedtuples... Hmm. :/

Looking into it...

**Comment by cculianu** [comment]
Ok, I think I managed to fix it with a semi-elegant work-around for deserialize.  The issue is we introduced new data types to encapsulate Addresses some time ago without any regression testing.

@qr1qr1  If you like, you can grab my branch to test my fix: https://github.com/cculianu/electrum/tree/fix_638

Tested here and works with daemon mode.

**Comment by qr1qr1** [comment]
Thank you cculianu. It works now. You are a ninja!
