### ISSUE TITLE
use a checkpoint to make sure ElectronCash settles on the BitcoinCash chain 

### ISSUE THREAD

**Issue by molecular** [fyookball/electrum#86]
@ecdsa suggested to use checkpointing in blockchain.py to make sure ElectronCash settles on the correct chain and connect to the correct servers.

**Comment by molecular** [comment]
I implemented this and am testing...

**Comment by molecular** [comment]
I tested above commit by cutting short blockchain_headers to contain 470000 blocks. Unfortunately something goes wrong in the aftermath:

```
[Blockchain] verify_chunk failed this block header 478559 is not the BitcoinCash fork block
[electrum.taborsky.cz] SSL certificate signed by CA
[electrum.taborsky.cz] connected
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/nick/bitcoin/electron-cash/lib/network.py", line 962, in run
    self.wait_on_sockets()
  File "/home/nick/bitcoin/electron-cash/lib/network.py", line 929, in wait_on_sockets
    self.process_responses(interface)
  File "/home/nick/bitcoin/electron-cash/lib/network.py", line 623, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/nick/bitcoin/electron-cash/lib/network.py", line 569, in process_response
    self.on_get_header(interface, response)
  File "/home/nick/bitcoin/electron-cash/lib/network.py", line 850, in on_get_header
    assert bh == interface.good
AssertionError
 ```

**Comment by molecular** [comment]
molecular/6e9203fcfa4554817351a25d19a342bbf889e5e3
